sixdegrees/config/routes.rb
Rails.application.routes.draw do
  resources :queries

end

sixdegrees/app/models/query.rb
class Query < ActiveRecord::Base
end

sixdegrees/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

sixdegrees/app/controllers/queries_controller.rb
class QueriesController < ApplicationController
  before_action :set_query, only: [:show, :edit, :update, :destroy]

  # GET /queries
  # GET /queries.json
  def index
    @queries = Query.all
  end

  # GET /queries/1
  # GET /queries/1.json
  def show
  end

  # GET /queries/new
  def new
    @query = Query.new
  end

  # GET /queries/1/edit
  def edit
  end

  # POST /queries
  # POST /queries.json
  def create
    @query = Query.new(query_params)

    respond_to do |format|
      if @query.save
        format.html { redirect_to @query, notice: 'Query was successfully created.' }
        format.json { render :show, status: :created, location: @query }
      else
        format.html { render :new }
        format.json { render json: @query.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /queries/1
  # PATCH/PUT /queries/1.json
  def update
    respond_to do |format|
      if @query.update(query_params)
        format.html { redirect_to @query, notice: 'Query was successfully updated.' }
        format.json { render :show, status: :ok, location: @query }
      else
        format.html { render :edit }
        format.json { render json: @query.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /queries/1
  # DELETE /queries/1.json
  def destroy
    @query.destroy
    respond_to do |format|
      format.html { redirect_to queries_url, notice: 'Query was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_query
      @query = Query.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def query_params
      params.require(:query).permit(:instructions, :query_string)
    end
end

sixdegrees/app/helpers/application_helper.rb
module ApplicationHelper
end

sixdegrees/app/helpers/queries_helper.rb
module QueriesHelper
end

sixdegrees/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sixdegrees</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

sixdegrees/app/views/queries/_form.html.erb
<%= form_for(@query) do |f| %>
  <% if @query.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@query.errors.count, "error") %> prohibited this query from being saved:</h2>

      <ul>
      <% @query.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :instructions %><br>
    <%= f.text_area :instructions %>
  </div>
  <div class="field">
    <%= f.label :query_string %><br>
    <%= f.text_field :query_string %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

sixdegrees/app/views/queries/edit.html.erb
<h1>Editing query</h1>

<%= render 'form' %>

<%= link_to 'Show', @query %> |
<%= link_to 'Back', queries_path %>

sixdegrees/app/views/queries/index.html.erb
<h1>Listing queries</h1>

<table>
  <thead>
    <tr>
      <th>Instructions</th>
      <th>Query string</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @queries.each do |query| %>
      <tr>
        <td><%= query.instructions %></td>
        <td><%= query.query_string %></td>
        <td><%= link_to 'Show', query %></td>
        <td><%= link_to 'Edit', edit_query_path(query) %></td>
        <td><%= link_to 'Destroy', query, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Query', new_query_path %>

sixdegrees/app/views/queries/new.html.erb
<h1>New query</h1>

<%= render 'form' %>

<%= link_to 'Back', queries_path %>

sixdegrees/app/views/queries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Instructions:</strong>
  <%= @query.instructions %>
</p>

<p>
  <strong>Query string:</strong>
  <%= @query.query_string %>
</p>

<%= link_to 'Edit', edit_query_path(@query) %> |
<%= link_to 'Back', queries_path %>